### ISSUE TITLE
Crash with Xaero's World Map

### ISSUE THREAD

**Issue by FruitW0rld** [jtorleonstudios/HUB-Library-Ferret#11]
Crash log:
[crash-2023-03-13_19.18.36-client.txt](https://github.com/jtorleonstudios/HUB-Library-Ferret/files/10962697/crash-2023-03-13_19.18.36-client.txt)

**Comment by jtorleonstudios** [comment]
You have: 
- awesomedungeon-forge-1.16.5-3.0.0.jar   
- awesomedungeonnether-forge-1.16.5-3.0.0.jar 
And the 3.0.0 is not compatible with library ferret 4.0.0, need 3.1.0.Please wait until all Awesome Dungeon mods are updated to support the new version of the Ferret libary

**But the error provided does not seem to come from one of my mods.** But I will try it with all mods once they are all updated to support the 4.0.0 version of the libraryferret.

I will confirm or not the problem once the tests are done with Xaero's World Map, even if I doubt that the problem comes from my mods.
