### ISSUE TITLE
[Forge 41.1.0] Version 2.5.0 does not work with Awesome Dungeon

### ISSUE THREAD

**Issue by TheRealMarine** [jtorleonstudios/HUB-Library-Ferret#5]
Version 2.5.0 does not work with Awesome Dungeon, What is the problem?

USELESS ERROR REMOVE (see history)

**Comment by AleFrech** [comment]
I encountered same problem tho I found out that This error happens with all related mod projects where "X" is a mod  that reqiures the libraryferret as a required dependency.

Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod "X" requires §6libraryferret§r §o2.0.0 or above§r
§7Currently, §6libraryferret§r§7 is §o1

**Comment by jtorleonstudios** [comment]
Don't update the mod, no mod requires version 2.5.0 yet

**Comment by AleFrech** [comment]
But if I dont update libraryferret to 2.5.0 the mod fails to load in Forge 41.1.0

**Comment by jtorleonstudios** [comment]
Yes it's normal, the old version not work with this version (see #2 )

**Comment by TheRealMarine** [comment]
> Don't update the mod, no mod requires version 2.5.0 yet

May i ask why you update the Mod without supporting already made mods (like Awesome Dungeons) and even tell us to not update?
It is contra productive to update a mod and then tell to not update the mod to the public.

**Comment by jtorleonstudios** [comment]
Because we use Cursegradle to retrieve our dependencies, we need the online file to be able to retrieve the file ID and add it to the gradle build.

So it's a very bad faith to say I didn't anticipate anyone, there is a note in every changelog that clearly states which version of the library to use! !!!. And moreover we made a communication to warn as every time!

May I ask why you don't read the changelog? **It's contra productive?!** 
![image](https://user-images.githubusercontent.com/89711083/182560077-da71143b-9335-44d1-8267-3d443bf5969b.png)
